version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com.br"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin2020"
    ports:
      - 8888:80
    depends_on:
      - db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
